### ISSUE TITLE
Add teardown_interval to close connections after certain amount of time has passed

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-output-redis#21]
The Shippers establish a TCP connection to Redis and never drop it, if you have a load balancer, the balance of load depends on the initial triaging by the load balancer. (in other words, once a running Shipper connects to a Redis it will stay connected to that Redis). At times the overwhelming majority are connected to a Redis instance.

Adding a teardown internal and closing the connection after several minutes will allow to release old connections and refresh the connection which is very useful for load balancing instances.

**Comment by jordansissel** [comment]
Related https://github.com/logstash-plugins/logstash-input-redis/issues/33 - let's discuss the possible solutions on that ticket first, and we can apply whatever is agreed-upon to both redis input and output. Deal? :)

**Comment by gmoskovicz** [comment]
Deal!

On Wednesday, December 9, 2015, Jordan Sissel <notifications@github.com>
wrote:

> Related logstash-plugins/logstash-input-redis#33
> <https://github.com/logstash-plugins/logstash-input-redis/issues/33> -
> let's discuss the possible solutions on that ticket first, and we can apply
> whatever is agreed-upon to both redis input and output. Deal? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-output-redis/issues/21#issuecomment-163431503>
> .
>


-- 

--
Gabriel Moskovicz | Support Engineer | +598 95-051-777
Uruguay

**Comment by gmoskovicz** [comment]
@jordansissel we will continue the discussion on that thread.

**Comment by suyograo** [comment]
Not applicable at this time. Closing
