### ISSUE TITLE
<LocalJumpError: unexpected next> for all logs

### ISSUE THREAD

**Issue by cromega** [logstash-plugins/logstash-output-redis#26]
https://github.com/logstash-plugins/logstash-output-redis/blob/v2.0.4/lib/logstash/outputs/redis.rb#L236 triggers a runtime error.

**Comment by cromega** [comment]
Hey,

After much time spent debugging this issue I can provide some more details.

While all log entries trigger the exception to be printed to stdout the logs actually get through to Redis. The main problem is the massive amounts of error logs this bug generates.

As I pointed out in the previous comment, the bug is caused by a `next` call which is not within an iterator context and it causes a (sort-of) syntax error.

[This](https://github.com/logstash-plugins/logstash-output-redis/blob/v2.0.4/lib/logstash/outputs/redis.rb#L153-L158) error handling block, if I'm correct, is to prevent the output pipeline from blowing up in case of an error. The code correctly catches `StandardError` only. However, this does not work very well with JRuby.

The error JRuby raises for an out-of-context `next` is `LocalJumpError`, which inherits from `StandardError`, even though it should inherit from `ScriptError` as is the case with MRI.

In my opinion the plugin should fatally blow up when execution reaches [here](https://github.com/logstash-plugins/logstash-output-redis/blob/v2.0.4/lib/logstash/outputs/redis.rb#L236)

The reason this bug went unnoticed during testing is the aforementioned exception catching block. During tests `@logger.warn` does not do anything.

I thought about issuing a PR but changing the erroneous `next` statement to `return` would not solve the underlying issue which caused this bug to go unnoticed in the first place (and it would definitely wouldn't prevent similar bugs from happening in the future)

**Comment by AlexClineBB** [comment]
I was able to change the affected line in `/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-2.0.4/lib/logstash/outputs/redis.rb` as a temporary workaround for this issue.

**Comment by blavoie** [comment]
got the same error... 
what to change precisely to overcome this flood of errors?
downgraded to 2.2.2....

**Comment by cromega** [comment]
@blavoie: `sed '236 s/next/return/' lib/logstash/outputs/redis.rb` is a temporary workaround.

**Comment by blavoie** [comment]
@cromega tks
Is the bug also there in LS 2.3.x series?

**Comment by tihakkar** [comment]
@blavoie Yes. I just saw the same issue after updating to LS 2.3.1

**Comment by colinsurprenant** [comment]
got PR #27 to fix this, I am hoping to push a new plugin version out today.

**Comment by colinsurprenant** [comment]
pushed new plugin version 2.0.5 which should fix this issue.

**Comment by bardoup** [comment]
I still got the problem with logstash 2.3.1 and plugin output-redis v 2.0.5

`{:timestamp=>"2016-04-25T11:56:13.643000+0200", :message=>"Error encoding event", :exception=>#<LocalJumpError: unexpected next>, :event=>#<LogStash::Event:0x3222d7dc @metadata_accessors=#<LogStash::Util::Accessors:0x4e6dbb4f @store={}, @lut={}>, @cancelled=false, @data={"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0x2dda9452 @store={"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, @lut={"host"=>[{"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, "host"], "port"=>[{"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, "port"], "type"=>[{"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, "type"], "zone"=>[{"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, "zone"], "site"=>[{"message"=>"<167>2016-04-25T09:54:33.866Z sv-t-nvm405.mipih.net Vpxa: verbose vpxa[FFE00B70] [Originator@6876 sub=PropertyProvider opID=HB-host-203@77224-2fb72a1d-50] RecordOp ASSIGN: info.progress, session[522608e0-c564-6831-d999-27b7506a6c9f]52bbc019-f080-42ac-5596-3c689220a68b. Applied change to temp map.", "@version"=>"1", "@timestamp"=>"2016-04-25T09:56:03.670Z", "host"=>"10.194.125.85", "port"=>62135, "type"=>"syslog", "zone"=>"int", "site"=>"tl"}, "site"]}>>, :level=>:warn}`
