### ISSUE TITLE
 redis output network errors should include context

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-redis#3]
(Migrated from https://github.com/elasticsearch/logstash/issues/1671)

A user on IRC reported tonight that the redis output showed this error (paraphrased):

Errno::EHOSTUNREACH: No route to host - SocketChannel.connect

This error is bad because it has no context. It would be more lovely and helpful to include the host and port that was involved in the failure. This is especially important because the redis output supports host setting having more than one entry.

**Comment by devpets** [comment]
Where is it possible to view the logs?

**Comment by untergeek** [comment]
I'm closing this with regards to the recent changes to the plugin, and that Logstash was a very different animal in January, 2015.  

If this issue comes up again, feel free to re-open or open a new issue.
