### ISSUE TITLE
Add RPOPLPUSH & LREM commands for redis reliable delivery

### ISSUE THREAD

**Issue by mostolog** [logstash-plugins/logstash-output-redis#40]
As exposed in https://github.com/logstash-plugins/logstash-input-redis/issues/51, to implement Redis reliable delivery, logstash redis output plugin should allow executing RPOPLPUSH & LREM commands.

**Comment by mostolog** [comment]
If I'm not wrong, this could be done with mode=template, specifying commands on template, if https://github.com/rsyslog/rsyslog-doc/issues/271 gets fixed

**Comment by jordansissel** [comment]
> with mode=template

I don't know what this means.

**Comment by mostolog** [comment]
@jordansissel wrong github project :upside_down_face:
