### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by mrjameshamilton** [logstash-plugins/logstash-output-redis#41]
I got the following error message which didn't say what the actual error was

`Pipeline aborted due to error {:exception=>"RuntimeError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-2.0.5/lib/logstash/outputs/redis.rb:115:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
`

Looking at the line of code the actual error is: "Must define queue, or key and data_type parameters"

**Comment by jsvd** [comment]
this is fixed in https://github.com/elastic/logstash/commit/b5643820172d53fbaef822740a8b3ae6590066b3, which will be included in logstash 2.4.1
