### ISSUE TITLE
logstash crashes when redis is restarted

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-output-redis#48]
When restarting redis, logstash will crash. This happens near immediately. @guyboertje 
```
{
	"timestamp": "2016-12-22T06:04:12.556000-0500",
	"message": "Failed to flush outgoing items",
	"outgoing_count": 8,
	" exception": "Redis::CannotConnectError",
	"backtrace": ["/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/li b/redis/client.rb:345:in `establish_connection'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/r edis/client.rb:101:in `connect'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis/client.rb:2 93:in `with_reconnect'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis/client.rb:100:in `co nnect'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis/client.rb:364:in `ensure_connected'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis/client.rb:221:in `process'",
	"/opt/logstash/ vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'",
	"/opt/logstash/vendor/bundle/jr uby/1.9/gems/redis-3.3.1/lib/redis/client.rb:220:in `process'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/red is-3.3.1/lib/redis/client.rb:120:in `call'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis. rb:1070:in `rpush'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'",
	"/entlogsrvbal801/opt/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'",
	"/entlogsrvbal80 1/opt/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'",
	"/opt/logstash/vendor/bundle/jru by/1.9/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3. 3.1/lib/redis.rb:1069:in `rpush'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-2.0.5/lib/ logstash/outputs/redis.rb:181:in `flush'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buf fer.rb:221:in `buffer_flush'",
	"org/jruby/RubyHash.java:1342:in `each'",
	"/opt/logstash/vendor/bundle/jruby/1.9/ gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0. 0.22/lib/stud/buffer.rb:193:in `buffer_flush'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stu d/buffer.rb:112:in `buffer_initialize'",
	"org/jruby/RubyKernel.java:1479:in `loop'",
	"/opt/logstash/vendor/bundl e/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"],
	"level": "warn"
}
```

**Comment by jordansissel** [comment]
I tried to reproduce this on Logstash 5.2.2 and I was unable.

Order of operations tried:

1. start redis-server
2. start logstash `bin/logstash -e 'output { redis { key => foo data_type => list } }'`
3. type a few lines
4. stop redis-server
5. observe logstash logging the following once per second: "Failed to send event to Redis" (same log message as reported)
6. observe logstash is still running
7. start redis-server
8. observe logstash is no longer logging the warning about redis being down
9. type a few lines again into logstash
10. observe logstash is still running happily and sending to redis
11. verify that the test key `foo` in redis has all the data

----

Here's what is happening:

Redis goes down, and Logstash notices. Logstash tries to resend the last failed request to redis  once per second  until redis is back online.

Logstash does not appear to crash.

**Comment by jordansissel** [comment]
It's possible the log message is too verbose, but the reported behavior (crash) is not something I am successfully reproducing.

Ideas? Are we sure Logstash is really crashing?

By "crash" I mean "terminates unexpectedly and is no longer running"

**Comment by jpcarey** [comment]
I tried to locally reproduce, and had no luck either. I'm collecting more information to see if I am missing something.

**Comment by guyboertje** [comment]
@whack outside of whether the problem is reproducible, there is a bug, I believe.

The redis client code throws a subclass of `RuntimeError` and the `Stud::Buffer #buffer_flush` method rescues a StandardError
The bug is that the output flush method does not trap the Redis Runtime error and retry.

**Comment by jpcarey** [comment]
@guyboertje @jordansissel just following up to see if we could safely handle the RuntimeError? I tried some further steps to reproduce with @GlenRSmith the other day, but unable to get logstash to a point where the original error in this gh issue is thrown. I was using the generator input though, where in the real world scenario I believe beats was being used. I'll try some further steps to reproduce, but if this can be fixed by catching the error - is there an absolute need to reproduce?

**Comment by jordansissel** [comment]
Hmm.. 

> The redis client code throws a subclass of RuntimeError and the Stud::Buffer #buffer_flush 

We should make the redis output no longer use Stud::Buffer. Logstash doesn't need this anymore.

**Comment by jordansissel** [comment]
@jpcarey When I mean I cannot reproduce, I mean I cannot reproduce the crash. I noted my steps in [this comment](https://github.com/logstash-plugins/logstash-output-redis/issues/48#issuecomment-284945472).

I don't think we necessarily need to reproduce, but I need to understand what is happening in order to fix the problem, otherwise any patch I contribute (without understanding of the problem) has a low probability of actually fixing the problem.

**Comment by jordansissel** [comment]
@jpcarey and I spoke on slack about this.

We can cause Logstash to crash if Redis restarts with this configuration *only* on Logstash 2.4.0:

```
% bin/logstash --log-in-json -e 'output { redis { key => foo data_type => list } }'
{"timestamp":"2017-05-10T12:59:19.137000-0700","message":"Pipeline main started"}
testing

^^ insert ok
--- stop redis
vvv now send new data, and Logstash will crash while logging in json.
test
LogStash::Json::GeneratorError: Cannot serialize instance of: LogStash::Json::GeneratorError
```

**Comment by jordansissel** [comment]
I tested this in Logstash 5.4.0 and the crash does not occur. I recommend upgrading from Logstash 2.4.0 to 5.4.0.
