### ISSUE TITLE
Request feature to be able to specify the field to send to redis.

### ISSUE THREAD

**Issue by truthadjustr** [logstash-plugins/logstash-output-redis#56]
Currently, I noticed that it sends the contents of the message field to redis and there is no setting for me to specify other field.

**Comment by jordansissel** [comment]
It's maybe not documented well, but the codec setting is intended to be used for this.

If you want your event as JSON, you can use `codec => json` in your redis output. If you want a specific field from your event, you can use the plain codec with the format setting; for example, to send the 'foo' field value, you can do: `output { redis { codec => plain { format => "%{foo}" } } }`

**Comment by truthadjustr** [comment]
Indeed. It works.
